export const GST_STATE_CODES = [
  { value: "01", label: "Jammu And Kashmir (01)" },
  { value: "02", label: "Himachal Pradesh (02)" },
  { value: "03", label: "Punjab (03)" },
  { value: "04", label: "Chandigarh (04)" },
  { value: "05", label: "Uttarakhand (05)" },
  { value: "06", label: "Haryana (06)" },
  { value: "07", label: "Delhi (07)" },
  { value: "08", label: "Rajasthan (08)" },
  { value: "09", label: "Uttar Pradesh (09)" },
  { value: "10", label: "Bihar (10)" },
  { value: "11", label: "Sikkim (11)" },
  { value: "12", label: "Arunachal Pradesh (12)" },
  { value: "13", label: "Nagaland (13)" },
  { value: "14", label: "Manipur (14)" },
  { value: "15", label: "Mizoram (15)" },
  { value: "16", label: "Tripura (16)" },
  { value: "17", label: "Meghalaya (17)" },
  { value: "18", label: "Assam (18)" },
  { value: "19", label: "West Bengal (19)" },
  { value: "20", label: "Jharkhand (20)" },
  { value: "21", label: "Odisha (21)" },
  { value: "22", label: "Chhattisgarh (22)" },
  { value: "23", label: "Madhya Pradesh (23)" },
  { value: "24", label: "Gujarat (24)" },
  { value: "25", label: "Daman And Diu (25)" },
  { value: "26", label: "Dadra And Nagar Haveli (26)" },
  { value: "27", label: "Maharashtra (27)" },
  { value: "29", label: "Karnataka (29)" },
  { value: "30", label: "Goa (30)" },
  { value: "31", label: "Lakshadweep (31)" },
  { value: "32", label: "Kerala (32)" },
  { value: "33", label: "Tamil Nadu (33)" },
  { value: "34", label: "Puducherry (34)" },
  { value: "35", label: "Andaman And Nicobar Islands (35)" },
  { value: "36", label: "Telangana (36)" },
  { value: "37", label: "Andhra Pradesh (37)" },
  { value: "38", label: "Ladakh (38)" }
];
